version: "3.8"

services:
  react-app:
    container_name: music-discovery-app-container
    build: .
    ports:
      - "8563:8563"
    volumes:
      - .:/app/Music-Discovery-Web-page
      - /app/Music-Discovery-Web-page/node_modules
    command: ["npm", "install", "&&", "npm", "run", "dev"]
    restart: always
