services:
  music-discovery-app:
    container_name: music-discovery-app-container
    build: .
    ports:
      - "8563:8563"
    command: ["npm", "install", "&&", "npm", "run", "dev"]
    restart: always
